
spring:
  application:
    name: lib-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5572}/${DB_NAME:library}
    username: ${DB_USER:admin-user}
    password: ${DB_PASSWORD:admin123}

  liquibase:
    enabled: true
    change-log: "classpath:/changelog/master.xml"
    driver-class-name: org.postgresql.Driver
    contexts: dev

server:
  port: 9068
